Add integration attributes to sdk
mParticle/mparticle-python-sdk pull request #26
Opened 2023-06-15 18:22 UTC by v-mamaya

## Summary
Added support for integration attributes in case they are needed to be included using the Python SDK

## Testing Plan
 - [X] Was this tested locally? 
 - I tested using unit tests, by asigning a dictionary with the [proper structure](https://docs.mparticle.com/developers/server/json-reference/#integration_attributes) to the batch object and checking the resulting output when it is assigned
 - I've sent some batches via Custom Feed using the Python SDK and verified the proper integration attributes appear on the batch in Livestream

2023-06-19 13:02 UTC, v-mamaya commented
hey @alexs-mparticle, can you take a look and let me know if we should change something?

2023-06-20 13:34 UTC, alexs-mparticle requested changes
Looks good. Only one style issue. I can release this once the change is made.

2023-06-20 13:34 UTC, alexs-mparticle commented on example_usage.py
> +    "someIntegrationAttribute":"value"
```suggestion
    "someIntegrationAttribute": "value"
```

2023-06-20 14:14 UTC, v-mamaya commented on example_usage.py
> +    "someIntegrationAttribute":"value"
Done!

2023-06-20 15:11 UTC, alexs-mparticle approved these changes

2023-06-20 15:25 UTC, merged